<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Makeup Shop - Cart</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <h1>Your Cart</h1>
        <nav>
            <ul>
            <li><a href="index.PHP">Home</a></li>
                <li><a href="products.PHP">Products</a></li>
                <li><a href="cart.PHP">Cart</a></li>
                <li><a href="hotdeals.PHP">Hot Deals</a></li>
                <li><a href="index.PHP">Home</a></li>
                <div class="input-container">
               
                <a href="LOGIN.PHP">
    <i   class="fa fa-user"></i>
</a>

            </ul>
        </nav>
    </header>
    <main>
        <section>
            <div class="cart-item">
                <h3>Product 1</h3>
                <p>Quantity: 1</p>
                <p>Price: $20.00</p>
            </div>
            <div class="cart-item">
                <h3>Product 2</h3>
                <p>Quantity: 2</p>
                <p>Price: $30.00</p>
            </div>
            <div class="cart-summary">
                <h3>Total: $50.00</h3>
                <button>Checkout</button>
            </div>
        </section>
    </main>
    <footer>
         
    </footer>
</body>
</html>
