<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Makeup Shop - Contact</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <h1>Contact Us</h1>
        <nav>
            <ul>
            <li><a href="index.PHP">Home</a></li>
                <li><a href="products.PHP">Products</a></li>
                <li><a href="cart.PHP">Cart</a></li>
                <li><a href="hotdeals.PHP">Hot Deals</a></li>
                <div class="input-container">
               
                <a href="LOGIN.PHP">
    <i   class="fa fa-user"></i>
</a>

 
            </ul>
        </nav>
    </header>
    <main>
        <section>
            <h2>Get in Touch</h2>
            <form>
                <label for="name">Name:</label>
                <input type="text" id="name" name="name">
                <label for="email">Email:</label>
                <input type="email" id="email" name="email">
                <label for="message">Message:</label>
                <textarea id="message" name="message"></textarea>
                <button type="submit">Send</button>
            </form>
        </section>
    </main>
    <footer>
        <p>&copy; 2024 Makeup Shop</p>
    </footer>
</body>
</html>
